spring-06
AndreiYazadzhi/ticket-project-1 pull request #10
Opened 2021-02-15 15:09 UTC by AndreiYazadzhi

2021-02-15 18:09 UTC, gigbat approved these changes

2021-02-16 15:20 UTC, KseniiaMakarova requested changes

2021-02-16 15:20 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/controller/OrderController.java
> +    @PutMapping("/complete")
why PutMapping?

2021-02-16 15:20 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/controller/OrderController.java
> +    public void completeOrder(OrderRequestDto dto) {
see task description - how should the data be passed to this method?

2021-02-16 15:20 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/controller/ShoppingCartController.java
> +    public ShoppingCartController(MovieSessionService movieSessionService,
let's either use `@Autowired` annotation above the constructor everywhere - or not use it at all

2021-02-16 15:20 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/model/dto/mapping/impl/request/UserRequestMapping.java
> +public class UserRequestMapping implements DtoRequestMapper<UserRequestDto, User> {
do we need this?

2021-02-16 15:20 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/model/dto/mapping/impl/response/OrderResponseMapper.java
> +                .format(DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm")));
let's move pattern to a constant field

2021-02-16 15:20 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/model/dto/mapping/impl/response/UserResponseMapping.java
> +
redundant empty line

2021-02-16 15:20 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/model/dto/response/UserResponseDto.java
> +    private String password;
see checklist - we should not expose the secure data, but should return id in all ResponseDtos

2021-02-16 15:20 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/model/dto/response/ShoppingCartResponseDto.java
> +    private List<Long> ticketsId;
```suggestion
    private List<Long> ticketIds;
```

2021-02-16 15:20 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/model/dto/response/OrderResponseDto.java
> +    private List<Long> ticketsId;
same

2021-02-16 15:20 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/model/dto/request/ShoppingCartRequestDto.java
> +public class ShoppingCartRequestDto {
do we use this?

2021-02-16 15:20 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/model/dto/request/OrderRequestDto.java
> +public class OrderRequestDto {
same - we don't need this

2021-02-16 15:20 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/model/dto/mapping/impl/response/UserResponseMapping.java
> +public class UserResponseMapping implements DtoResponseMapper<UserResponseDto, User> {
```suggestion
public class UserResponseMapper implements DtoResponseMapper<UserResponseDto, User> {
```

2021-02-16 15:20 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/model/dto/response/ShoppingCartResponseDto.java
> +public class ShoppingCartResponseDto {
where is the mapper for ShoppingCart?

2021-02-16 15:20 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/security/AuthenticationServiceImpl.java
> +        if (user.get().getPassword()
we should not change this logic - this does not make sense at the moment

2021-02-16 15:20 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/service/UserService.java
> +    User getByEmail(String email);
same

2021-02-16 15:20 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/service/impl/UserServiceImpl.java
> +    }
same

2021-02-17 05:59 UTC, KseniiaMakarova requested changes

2021-02-17 05:59 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/controller/UserController.java
> +    public UserController(DtoResponseMapper<UserResponseDto, User> responseMapper,
add annotation

2021-02-17 05:59 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/controller/UserController.java
> +    @GetMapping
what about mapping here?

2021-02-17 05:59 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/model/dto/mapping/impl/response/OrderResponseMapper.java
> +        orderResponseDto.setUserEmail(order.getUser().getEmail());
what about ticketIds?

2021-02-17 05:59 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/model/dto/response/OrderResponseDto.java
> +    private String userEmail;
```suggestion
    private String userEmail;
    private List<Long> ticketIds;
```

2021-02-17 05:59 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/model/dto/response/MovieResponseDto.java
> +    private Long id;
let's set it in mapper

2021-02-17 05:59 UTC, KseniiaMakarova commented on src/main/java/com/hibernate/model/dto/response/MovieSessionResponseDto.java
> +    private Long id;
same here

2021-02-17 09:59 UTC, KseniiaMakarova approved these changes

2021-02-17 10:16 UTC, merged