hibernate-05
AndreiYazadzhi/ticket-project-1 pull request #5
Opened 2021-02-02 12:00 UTC by AndreiYazadzhi

2021-02-02 14:18 UTC, Fedich09 requested changes

2021-02-02 14:18 UTC, Fedich09 commented on src/main/java/com/hibernate/service/impl/AuthenticationServiceImpl.java
> +        String hashedPassword = HashUtil.hashPassword(password, salt);
```suggestion
        
```
You should create salt and hash password in UserService add() method.

2021-02-02 14:18 UTC, Fedich09 commented on src/main/java/com/hibernate/service/impl/AuthenticationServiceImpl.java
> +        user.setSalt(salt);
```suggestion
        user.setPassword(password);
```
same here

2021-02-02 14:18 UTC, Fedich09 commented on src/main/java/com/hibernate/service/impl/AuthenticationServiceImpl.java
> +        String pass = user.getPassword();
```suggestion

```

2021-02-02 14:18 UTC, Fedich09 commented on src/main/java/com/hibernate/service/impl/UserServiceImpl.java
> +    public User add(User user) {
```suggestion
    public User add(User user) {
```
You should create salt and hash password in UserService add() method.

2021-02-02 14:36 UTC, Fedich09 approved these changes

2021-02-02 17:17 UTC, dmytro-hryhoruk requested changes

2021-02-02 17:17 UTC, dmytro-hryhoruk commented on src/main/java/com/hibernate/dao/impl/UserDaoImpl.java
> +                    .setParameter("email", email).uniqueResultOptional();
```suggestion
            return session.createQuery("from User where email = :email", User.class)
                    .setParameter("email", email)
                    .uniqueResultOptional();
```

2021-02-02 17:17 UTC, dmytro-hryhoruk commented on src/main/java/com/hibernate/service/impl/AuthenticationServiceImpl.java
> +        User user = userService.getByEmail(email);
Let's return optional from service too, and check here using isPresent()

2021-02-03 11:48 UTC, dmytro-hryhoruk approved these changes

2021-02-03 12:00 UTC, merged